require 'lib/vagrantfile_helper'

Vagrant::Config.run do |config|
  include VagrantfileHelper

  set_defaults(config, 'mqseries-centos64')

  # Forward a port from the guest to the host
  config.vm.forward_port "mqseries_listener", 1414, 1414
end

