Vagrant::Config.run do |config|
  vm_type = 'mqseries'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'centos60_64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://dl.dropbox.com/u/38777387/centos60_64-20110901.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.vagrant.local"

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.forward_port "mqseries_listener", 1414, 1414

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-centos64.pp"
    puppet.module_path = '../modules'
  end
end

