---
- include: ./mapnik-deps.yml
- name: Download Mapnik source
  git: repo=https://github.com/mapnik/mapnik.git
       dest=/tmp/mapnik
       recursive=yes
       version=2.3.x
       force=yes
       accept_hostkey=yes
- name: Configure Mapnik build
  shell: /usr/bin/python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/ PG_CONFIG=/usr/pgsql-9.4/bin/pg_config BOOST_INCLUDES=/usr/local/include/boost/ > /tmp/mapnik-configure.log
         chdir=/tmp/mapnik
         creates=/tmp/mapnik/config.py
- name: Build Mapnik
  shell: /usr/bin/python scons/scons.py > /tmp/mapnik-build.log
         chdir=/tmp/mapnik
         creates=/tmp/mapnik/src/libmapnik.so
- name: Install Mapnik (requires sudo)
  shell: /usr/bin/python scons/scons.py install > /tmp/mapnik-install.log
         chdir=/tmp/mapnik
         creates=/usr/local/lib/libmapnik.so.2.3
- name: Run ldconfig to update some bindings or something (requires root)
  shell: /sbin/ldconfig && touch /tmp/ldconfig-post-mapnik.success
         creates=/tmp/ldconfig-post-mapnik.success
- name: Copy Mapnik fonts
  shell: /bin/cp --recursive /tmp/mapnik/fonts /usr/local/lib/mapnik/fonts
         creates=/usr/local/lib/mapnik/fonts/dejavu-fonts-ttf-2.33/ttf/DejaVuSans.ttf

