Vagrant.configure("2") do |config|
  vm_type = 'plain'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'ubuntu/trusty64'

  # The url from where the 'config.vm.box' box will be fetched.
  # config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/trusty/trusty-server-cloudimg-amd64-juju-vagrant-disk1.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.ubuntu64.vagrantup.com"

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-plain-ubuntu.yml"
    ansible.verbose = "vv" # v, vv, vvv, vvvv
  end

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 22, host: 2194, id: "ssh", auto_correct: true

  # Share a folder to the VM (host path, guest path)
  config.vm.synced_folder "../share", "/vagrant-share"
  #config.vm.synced_folder ENV['HOME'], "/home/vagrant/home"
end
