Vagrant.configure("2") do |config|
  vm_type = 'plain'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'precise64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.precise64.vagrantup.com"

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.forward_port 80, 8080, :auto => true

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-plain-ubuntu.yml"
    ansible.verbose = "vvv" # v, vv, vvv, vvvv
  end

  config.vm.provider "virtualbox" do |vb|
    # Share a folder to the VM (id, guest path, host path)
    vb.share_folder "vagrant-share", "/vagrant-share", "../share"
    vb.share_folder "source", "/home/vagrant/home", ENV['HOME']

    # https://gist.github.com/2155825
    vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--hostiocache', 'on' ]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1' ]
  end
end

