Vagrant::Config.run do |config|
  vm_type = 'go'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'lucid64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://files.vagrantup.com/lucid64.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.lucid64.vagrant.local"

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.forward_port "go_http", 8153, 8153, :auto => true
  config.vm.forward_port "go_https", 8154, 8154, :auto => true

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-ubuntu64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"

  # Set memory allocated to the VM in MB
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end
end

