require 'lib/vagrantfile_helper'

Vagrant::Config.run do |config|
  include VagrantfileHelper

  set_defaults(config, 'ubuntu64', 'go')

  # Set memory allocated to the VM in MB
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port "go_http", 8153, 8153
  config.vm.forward_port "go_https", 8154, 8154
end

