Vagrant.configure("2") do |config|
  vm_type = 'lab' 

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'precise64-unity'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://dl.dropbox.com/u/36836372/precise64-unity-20120504.box'

  # Assign this VM a unique hostname
  #config.vm.host_name = "#{ENV['USER']}.#{vm_type}.precise64.vagrantup.com"
  config.vm.host_name = "#{vm_type}.vagrantup.com"

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-lab-ubuntu.yml"
    ansible.verbose = "vv" # v, vv, vvv, vvvv
  end

  # Share a folder to the VM (host path, guest path)
  config.vm.synced_folder "../share", "/vagrant-share"

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    # Boot with a GUI so you can see the screen. (Default is headless)
    vb.gui = true

    # Set memory allocated to the VM in MB
    vb.customize ['modifyvm', :id, '--memory', '2048']
    vb.customize ['modifyvm', :id, '--cpus', '1']
    vb.customize ['modifyvm', :id, '--vram', '128']
    vb.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']

    # Enable sound
    vb.customize ['modifyvm', :id, '--audio', 'coreaudio']
    vb.customize ['modifyvm', :id, '--audiocontroller', 'ac97']

    # Enable shared clipboard
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']

    # https://gist.github.com/2155825
    vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--hostiocache', 'on' ]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1' ]
  end
end

