Vagrant.configure("2") do |config|
  vm_type = 'maptiles'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'hashicorp/precise64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://hashicorp-files.vagrantup.com/precise64.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.precise64.vagrantup.com"

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-#{vm_type}-ubuntu.yml"
    ansible.verbose = "vv" # v, vv, vvv, vvvv
  end

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.network "forwarded_port", guest: 22, host: 2195, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 12195, auto_correct: true # Apache httpd with mod_tile
  config.vm.network "forwarded_port", guest: 5432, host: 5432, auto_correct: true # PostgreSQL server

  # Share a folder to the VM (host path, guest path)
  config.vm.synced_folder "../share", "/vagrant-share"
  config.vm.synced_folder ENV['HOME'], "/home/vagrant/home"

  config.vm.provider "virtualbox" do |vb|
    # https://gist.github.com/2155825
    vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--hostiocache', 'on' ]
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1' ]
  end
end
