Vagrant::Config.run do |config|
  vm_type = 'gnome'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'centos62_64-gnome'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://dl.dropbox.com/u/36836372/centos62_64-gnome-20120313.box'

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.vagrantup.com"

  # Enable provisioning with Puppet stand alone
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-centos64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"
  config.vm.share_folder "source", "/home/vagrant/home", ENV['HOME']

  # Set memory allocated to the VM in MB
  config.vm.customize ['modifyvm', :id, '--memory', '2048']
  config.vm.customize ['modifyvm', :id, '--cpus', '2']
  config.vm.customize ['modifyvm', :id, '--vram', '16']
  config.vm.customize ['modifyvm', :id, '--accelerate2dvideo', 'on']
end

