require 'lib/vagrantfile_helper'

Vagrant::Config.run do |config|
  include VagrantfileHelper

  set_defaults(config, 'centos64', 'gnome')

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  # Set memory allocated to the VM in MB
  config.vm.customize do |vm|
    vm.memory_size = 1024
  end

  # Forward a port from the guest to the host
  # config.vm.forward_port "http", 80, 8080
end

