Vagrant::Config.run do |config|
  vm_type = 'gnome'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'centos60_64-gnome'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://dl.dropbox.com/u/36836372/centos60_64-gnome-20110819.box'

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.vagrant.local"

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.forward_port 'http', 80, 8080, :auto => true

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-centos64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"

  # Set memory allocated to the VM in MB
  config.vm.customize do |vm|
    vm.memory_size = 512
  end
end

