Vagrant::Config.run do |config|
  vm_type = 'plain'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'centos62_64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://dl.dropbox.com/u/36836372/centos62_64-nochef-20120508.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.vagrant.local"

  # Forward a port from the guest to the host (id, guest port, host port)
  #config.vm.forward_port 80, 8080, :auto => true

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-centos64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"
  config.vm.share_folder "source", "/home/vagrant/home", ENV['HOME']
end

