Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'
  config.vm.synced_folder '../share/conf/mapnik', '/vagrant-share/conf/mapnik'

  keypair_name = ENV['EC2_KEYPAIR']

  config.vm.provider :aws do |aws, override|
    aws.ami = 'ami-abeb9e91' # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type, ap-southeast-2
    aws.instance_type = 't2.small' # t2.micro, t2.small, t2.medium, m3.medium
    aws.keypair_name = keypair_name
    aws.region = 'ap-southeast-2'
    aws.security_groups = ['port-22', 'ports-80-443']

    # https://github.com/mitchellh/vagrant-aws/pull/26
    aws.user_data = "#!/bin/sh\nsed -i -e 's/^\\(Defaults.*requiretty\\)/#\\1/' /etc/sudoers\n"

    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = ENV['AWS_SSH_KEY'] || "#{ENV['HOME']}/.ec2/#{keypair_name}.pem"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'playbook-maptiles-aws.yml'
    ansible.sudo = true
    ansible.verbose = 'vv' # v, vv, vvv, vvvv
    ansible.extra_vars = {
      username: 'ubuntu'
    }
  end
end

