require 'lib/vagrantfile_helper'

Vagrant::Config.run do |config|
  include VagrantfileHelper

  set_defaults(config, 'ibmrtc-centos64')

  # Set memory allocated to the VM in MB
  config.vm.customize do |vm|
    vm.memory_size = 2048
  end

  # Forward a port from the guest to the host
  config.vm.forward_port "rtc_http", 9080, 9080
  config.vm.forward_port "rtc_https", 9443, 9443
end

