require 'lib/vagrantfile_helper'

Vagrant::Config.run do |config|
  include VagrantfileHelper

  set_defaults(config, 'centos64', 'webdav')

  config.vm.host_name = 'ldap.example.com'

  # Forward a port from the guest to the host
  config.vm.forward_port "http", 80, 9081
end

