include apps::chrome
include apps::evince
include avahi::disable
include debrepos::partner
include editor::idea-ultimate
include editor::janus
include editor::vimx
include fonts::microsoft
include iptables::disable
include java::oraclejdk7
include rvm::system_install
include timezone::sydney
include ubuntu::fixgroup
include ubuntu::keybindings
include utils::base
include vcs::gitconfig
include vcs::mercurial_keyring
include utils::netcat
include xwindows::hideerrors

