---
- yum: name={{ item }} enablerepo=epel,elgis,pgdg94
  with_items:
    - postgresql94-devel
    - postgis2_94
    - postgis2_94-client
    - postgis2_94-devel
    - postgis2_94-utils
    - pgrouting_94

