---
- name: Are GDAL dependencies in place?
  command: /bin/ls /usr/lib64/libpoppler.so.5
  register: libpoppler5_present
  ignore_errors: True
- name: Download lcms-libs RPM from CentOS 6 repo
  get_url: url=http://mirror.centos.org/centos/6/os/x86_64/Packages/lcms-libs-1.19-1.el6.x86_64.rpm
           dest=/tmp/lcms-libs-1.19-1.el6.x86_64.rpm
           sha256sum=769fcbf5d06ead35546b3e009dc47c122ae8ffc691523c2760f4ca3250c41756
  when: libpoppler5_present|failed
- name: Download poppler RPM from CentOS 6 repo
  get_url: url=http://mirror.centos.org/centos/6/os/x86_64/Packages/poppler-0.12.4-3.el6_0.1.x86_64.rpm
           dest=/tmp/poppler-0.12.4-3.el6_0.1.x86_64.rpm
           sha256sum=9494e19ac5ca93b29b3b969262c5e63b8e99bcc42ef3eaca1ae57779f51c5958
  when: libpoppler5_present|failed
- name: Extract files from lcms-libs RPM
  shell: /usr/bin/rpm2cpio /tmp/lcms-libs-1.19-1.el6.x86_64.rpm | /bin/cpio -idmv
         chdir=/
         creates=/usr/lib64/liblcms.so.1
  when: libpoppler5_present|failed
- name: Extract files from poppler RPM
  shell: /usr/bin/rpm2cpio /tmp/poppler-0.12.4-3.el6_0.1.x86_64.rpm | /bin/cpio -idmv
         chdir=/
         creates=/usr/lib64/libpoppler.so.5
  when: libpoppler5_present|failed
- yum: name={{ item }} enablerepo=epel,elgis,pgdg94
  with_items:
    - postgresql94-devel
    - postgis2_94
    - postgis2_94-client
    - postgis2_94-devel
    - postgis2_94-utils
    - pgrouting_94

