---
- lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf line='host all all 0.0.0.0/0 md5' state=present
  sudo_user: postgres
  notify:
    - restart postgresql
- lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf line="listen_addresses = '*'" state=present
  sudo_user: postgres
  notify:
    - restart postgresql

