---
- apt: pkg={{ item }}
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
- name: add {{ username }} user to postgres group
  user: name={{ username }} groups=postgres append=yes
- service: name=postgresql enabled=yes state=started
- name: Is {{ username }} a role in PostgreSQL?
  shell: /usr/bin/psql --command="\du" | /bin/grep --quiet {{ username }}
  sudo_user: postgres
  register: postgres_role_vagrant_exists
  ignore_errors: True
- name: Create {{ username }} role in PostgreSQL
  shell: /usr/bin/psql --command="create role \"{{ username }}\" with superuser createdb createrole login password '{{ username }}'"
  sudo_user: postgres
  when: postgres_role_vagrant_exists|failed

