---
- yum: name=libselinux-python
- lineinfile: dest=/etc/yum.repos.d/CentOS-Base.repo line="exclude=postgres*" insertafter="^\[base\]$"
  ignore_errors: True
- lineinfile: dest=/etc/yum.repos.d/CentOS-Base.repo line="exclude=postgresql*" insertafter="^\[updates\]$"
  ignore_errors: True
- lineinfile: dest=/etc/yum.repos.d/amzn-main.repo line="exclude=postgres*" insertafter="^\[amzn-main\]$"
  ignore_errors: True
- lineinfile: dest=/etc/yum.repos.d/amzn-updates.repo line="exclude=postgres*" insertafter="^\[amzn-updates\]$"
  ignore_errors: True
#- yum: name=/vagrant-share/repos/pgdg-centos94-9.4-1.noarch.rpm
- template: src=../templates/yum.repo.j2
            dest=/etc/yum.repos.d/pgdg-94.repo
            owner=root group=root mode=0644
  with_items:
    - { id: 'pgdg94',
        name: 'PostgreSQL 9.4 6 - x86_64',
        baseurl: 'http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64',
        enabled: 1,
        gpgcheck: 0,
        gpgkey: False }
  #with_items:
    #- { id: 'pgdg94',
        #name: 'PostgreSQL 9.4 $releasever - $basearch',
        #baseurl: 'http://yum.postgresql.org/9.4/redhat/rhel-$releasever-$basearch',
        #enabled: 1,
        #gpgcheck: 0,
        #gpgkey: False }

