Vagrant.configure("2") do |config|
  vm_type = 'gui'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'lubuntu-desktop'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'https://dl.dropboxusercontent.com/u/36836372/lubuntu-desktop-20141028.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.ubuntu64.vagrantup.com"

  # Enable provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-gui-ubuntu.yml"
    ansible.verbose = "vv" # v, vv, vvv, vvvv
  end

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.network "forwarded_port", guest: 22, host: 2198, id: "ssh", auto_correct: true

  # Share a folder to the VM (host path, guest path)
  config.vm.synced_folder "../share", "/vagrant-share"
  config.vm.synced_folder ENV['HOME'], "/home/vagrant/home"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "#{vm_type}-ubuntu64"

    # Boot with a GUI so you can see the screen. (Default is headless)
    vb.gui = true

    # Set memory allocated to the VM in MB
    vb.customize ['modifyvm', :id, '--memory', '2048']
    vb.customize ['modifyvm', :id, '--cpus', '2']
    vb.customize ['modifyvm', :id, '--vram', '128']
    vb.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
    vb.customize ['modifyvm', :id, '--accelerate3d', 'on']

    # Enable sound
    vb.customize ['modifyvm', :id, '--audio', 'coreaudio']
    vb.customize ['modifyvm', :id, '--audiocontroller', 'ac97']

    # Disable shared clipboard
    vb.customize ['modifyvm', :id, '--clipboard', 'hosttoguest']
  end
end

