Vagrant::Config.run do |config|
  vm_type = 'postgres'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'ubuntu/trusty64'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.ubuntu64.vagrantup.com"

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.forward_port 5432, 5432, :auto => true # PostgreSQL server port
  config.vm.forward_port 3000, 13000, :auto => true # Rails server port

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-ubuntu64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"
  config.vm.share_folder "source", "/home/vagrant/home", ENV['HOME']
end
