Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'lubuntu-desktop'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'https://dl.dropboxusercontent.com/u/36836372/lubuntu-desktop-20141028.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.nodejs.ubuntu64.vagrantup.com"

  # Provision VM with Ansible (with workaround for Windows)
  require 'rbconfig'
  is_windows_host = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
  if is_windows_host
    # Run Ansible on VM using shell provisioning (for Windows hosts)
    config.vm.provision "shell" do |sh|
      sh.path = "provision.sh"
      sh.args = "playbook-nodejs-ubuntu64.yml"
    end
  else
    # Standard Ansible provisioning (for Mac and Linux hosts)
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-nodejs-ubuntu64.yml"
      ansible.verbose = "vv" # v, vv, vvv, vvvv
    end
  end

  # Forward a port from the guest to the host
  config.vm.network "forwarded_port", guest: 22, host: 2193, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true

  # Share a folder to the VM (host path, guest path)
  config.vm.synced_folder "../share", "/vagrant-share"
  config.vm.synced_folder ENV['HOME'], "/home/vagrant/home"
  if is_windows_host
    config.vm.synced_folder "../modules", "/modules"
    config.vm.synced_folder "../share", "/share"
  end

  config.vm.provider "virtualbox" do |vb|
    # Boot with a GUI so you can see the screen. (Default is headless)
    vb.gui = true

    # Set memory allocated to the VM in MB
    vb.customize ['modifyvm', :id, '--memory', '2048']
    vb.customize ['modifyvm', :id, '--cpus', '1']
    vb.customize ['modifyvm', :id, '--vram', '128']
    vb.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
    vb.customize ['modifyvm', :id, '--accelerate3d', 'on']

    # Enable sound
    if is_windows_host
      vb.customize ['modifyvm', :id, '--audio', 'dsound']
    else
      vb.customize ['modifyvm', :id, '--audio', 'coreaudio']
    end
    vb.customize ['modifyvm', :id, '--audiocontroller', 'ac97']

    # Enable shared clipboard
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
end

