---
- include: ../../debrepos/playbooks/openstreetmap.yml
- include: ../../apache/playbooks/apache2.yml
- apt: pkg=python-software-properties state=present
- name: Enable mod_tile in the apache config
  debconf: name='libapache2-mod-tile' question='libapache2-mod-tile/enablesite' vtype='boolean' value='true'
- name: Do not download coastlines, we will do that separately
  debconf: name='openstreetmap-mapnik-carto-stylesheet-data' question='openstreetmap-mapnik-carto-stylesheet-data/dloadcoastlines' vtype='boolean' value='false'
- name: Create a PostGIS database
  debconf: name='openstreetmap-postgis-db-setup' question='openstreetmap-postgis-db-setup/initdb' vtype='boolean' value='true'
- name: Set name of PostGIS database to osm
  debconf: name='openstreetmap-postgis-db-setup' question='openstreetmap-postgis-db-setup/dbname' vtype='string' value='osm'
- name: Set users that should have access to the PostGIS database
  debconf: name='openstreetmap-postgis-db-setup' question='openstreetmap-postgis-db-setup/grant_user' vtype='string' value='www-data vagrant'
- apt: pkg=libapache2-mod-tile state=present
- service: name=renderd enabled=yes state=started

