Vagrant::Config.run do |config|
  vm_type = 'sonar'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = 'precise64'

  # The url from where the 'config.vm.box' box will be fetched.
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  # Assign this VM a unique hostname
  config.vm.host_name = "#{ENV['USER']}.#{vm_type}.precise64.vagrantup.com"

  # Forward a port from the guest to the host (id, guest port, host port)
  config.vm.forward_port 9000, 9000, :auto => true # Sonar Web interface port
  config.vm.forward_port   80, 8080, :auto => true # Apache reverse proxy port
  config.vm.forward_port 5432, 5432, :auto => true # PostgreSQL database port

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "#{vm_type}-ubuntu64.pp"
    puppet.module_path = '../modules'
  end

  # Share a folder to the VM (id, guest path, host path)
  config.vm.share_folder "vagrant-share", "/vagrant-share", "../share"

  # Set memory allocated to the VM in MB
  config.vm.customize ['modifyvm', :id, '--memory', '1024']
end

